### ISSUE TITLE
Automatically mount data in the database to make testing easier

### ISSUE THREAD

**Issue by Ullaakut** [Ullaakut/Bloggo#24]
- [x] Manually fill the db using `adminer`
- [ ] Dump the db into a `.sql` file
- [ ] Mount this file like this:

```
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/blog_posts.sql:/docker-entrypoint-initdb.d/01-blog_posts.sql
      - ./data/users.sql:/docker-entrypoint-initdb.d/02-users.sql
```
